name: filexa
description: Filexa Downloader
publish_to: "none"

version: 1.17.0+33

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.10.0
  path_provider: ^2.1.6
  path: ^1.9.1
  open_filex: ^4.5.0
  share_plus: ^11.0.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true